################################################################################
# Substitution Variables
################################################################################
substitutions:
  device_name: esphome_room_sensors_ESP8266
  device_friendly_name: ESPHome Room Sensors
  device_ip_address: xxx.xxx.xxx.xxx
  device_sampling_time: 30s

################################################################################
# Globals
################################################################################
globals: ##to set default reboot behavior
  - id: wifi_connection
    type: bool
    restore_value: no
    initial_value: "false"

################################################################################
# Board Configuration
################################################################################
esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}

esp8266:
  board: esp01_1m

################################################################################
# Enable logging
################################################################################
logger:
  baud_rate: 0
  logs:
    sensor: INFO
    binary_sensor: INFO
    text_sensor: INFO

################################################################################
# Enable Home Assistant API
################################################################################
api:
  reboot_timeout: 0s
  encryption:
    key: !secret api_encryption_key

ota:
  safe_mode: true
  reboot_timeout: 10min
  num_attempts: 5
  password: !secret web_server_password

################################################################################
# WiFi
################################################################################
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

  manual_ip:
    static_ip: ${device_ip_address}
    gateway: !secret gateway_address
    subnet: !secret subnet_address

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_friendly_name}
    password: !secret web_server_password

################################################################################
# Web Server
################################################################################
web_server:
  port: 80
  auth:
    username: !secret web_server_user
    password: !secret web_server_password
  local: true

captive_portal:

################################################################################
# Status led
################################################################################
status_led:
  pin:
    number: 2
    inverted: false # Depends on your board and preferances

################################################################################
# I2C
################################################################################
i2c:
  sda: GPIO4
  scl: GPIO5
  scan: false # Set to true to find new devices

################################################################################
# UART
################################################################################
uart:
  id: ${device_internal_name}_uart_presence
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

################################################################################
# LD2410 Sensor
################################################################################
ld2410:
  timeout: 5s
  max_move_distance: 6m
  max_still_distance: 0.75m

################################################################################
# Time Sensor
################################################################################
time:
  - platform: homeassistant
    id: internal_time

################################################################################
# Text Sensors
################################################################################
text_sensor:
  #-------------------------------------------------------------------------------
  # ESP32 internal sensors
  #-------------------------------------------------------------------------------
  - platform: wifi_info
    ip_address:
      name: IP Address
      id: ${device_internal_name}_ip_address
    ssid:
      name: Connected SSID
      id: ${device_internal_name}_connected_ssid
    mac_address:
      name: Mac Wifi Address
      id: ${device_internal_name}_mac_address

  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true

  #-------------------------------------------------------------------------------
  # Custom Text sensors
  #-------------------------------------------------------------------------------
  - platform: template
    name: Uptime Human Readable
    id: ${device_internal_name}_uptime_human
    icon: mdi:clock-start

################################################################################
# Binary Sensors
################################################################################
binary_sensor:
  # ESP Status
  - platform: status
    name: "Status"
    id: ${device_internal_name}_device_status

  # LD2410
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target

  # Presence
  - platform: homeassistant
    id: presence
    entity_id: binary_sensor.${device_internal_name}_presence
    internal: True

sensor:
  #-------------------------------------------------------------------------------
  # ESP Generic Sensors
  #-------------------------------------------------------------------------------

  # WiFi
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    id: ${device_internal_name}_wifi_signal_sensor
    update_interval: ${device_sampling_time}

  # Uptime
  - platform: uptime
    name: "Uptime Sensor"
    id: ${device_internal_name}_uptime_sensor
    update_interval: ${device_sampling_time}
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: ${device_internal_name}_uptime_human
            state: !lambda |-
              int seconds = round(id(${device_internal_name}_uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

  #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  # Additional sensors
  #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  #-------------------------------------------------------------------------------
  # DHT22
  #-------------------------------------------------------------------------------
  - platform: dht
    pin: GPIO16
    temperature:
      name: "Temperature"
      id: ${device_name}_temperature
    humidity:
      name: "Humidity"
      id: ${device_name}_humidity
    model: DHT22
    update_interval: ${device_sampling_time}

  #-------------------------------------------------------------------------------
  # GY-302/BH1750 Light Sensor (0x23)
  #-------------------------------------------------------------------------------
  - platform: bh1750
    name: "Illuminance"
    id: illuminance
    address: 0x23
    update_interval: ${device_sampling_time}

  #-------------------------------------------------------------------------------
  # CCS811 Air Quality Control Sensor (0x5A)
  #-------------------------------------------------------------------------------
  - platform: ccs811
    eco2:
      name: "eCO2 Value"
      id: ${device_internal_name}_eco2
    tvoc:
      name: "Total Volatile Organic Compound"
      id: ${device_internal_name}_tvoc
      icon: mdi:heat-wave
    version:
      name: CCS811 Version
      id: ${device_internal_name}_ccs811_version
    address: 0x5A
    temperature: ${device_internal_name}_dallas_temperature
    humidity: ${device_internal_name}_relative_humidity
    update_interval: ${device_sampling_time}

  #-------------------------------------------------------------------------------
  # LD2410D Millimeter Wave Sensor (UART)
  #-------------------------------------------------------------------------------
  - platform: ld2410
    moving_distance:
      name: Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance

################################################################################
# Switch
################################################################################
switch:
  - platform: restart
    name: "Restart"
    id: device_restart

  - platform: safe_mode
    name: Use Safe Mode
    id: device_safe_mode

################################################################################
# Interval
################################################################################
interval:
  - interval: 10s
    then:
      - if:
          condition:
            wifi.connected:
          then:
            - lambda: |-
                id(wifi_connection) = true;
          else:
            - lambda: |-
                id(wifi_connection) = false;
