################################################################################
# Substitution Variables
################################################################################
substitutions:
  device_name: esphome_room_sensors
  device_friendly_name: ESPHome Room Sensors
  device_ip_address: xxx.xxx.xxx.xxx
  device_sampling_time: 30s

################################################################################
# Globals
################################################################################
globals: ##to set default reboot behavior
  - id: wifi_connection
    type: bool
    restore_value: no
    initial_value: "false"

################################################################################
# Board Configuration
################################################################################
esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino
    #version: 2.0.9 # Optional

################################################################################
# Enable logging
################################################################################
logger:
  logs:
    sensor: INFO
    binary_sensor: INFO
    text_sensor: INFO

################################################################################
# Enable Home Assistant API
################################################################################
api:
  reboot_timeout: 0s
  encryption:
    key: !secret api_encryption_key

ota:
  safe_mode: true
  reboot_timeout: 10min
  num_attempts: 5
  password: !secret web_server_password

################################################################################
# WiFi
################################################################################
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

  manual_ip:
    static_ip: ${device_ip_address}
    gateway: !secret gateway_address
    subnet: !secret subnet_address

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_friendly_name}
    password: !secret web_server_password

captive_portal:

################################################################################
# Bluetooth
################################################################################
# Do not enable the web server if there is the bluetooth proxy or tracker!!!
# Bluetooth Low Energy Tracker Hub
bluetooth_proxy:
  active: true

esp32_ble_tracker:
  id: ${device_name}_ble_tracker
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

################################################################################
# Status led
################################################################################
status_led:
  pin:
    number: 2
    inverted: false # Depends on your board and preferances

################################################################################
# I2C
################################################################################
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: false # Set to true to find new devices

################################################################################
# UART
################################################################################
uart:
  id: ${device_internal_name}_uart_presence
  tx_pin: GPIO17
  rx_pin: GPIO18
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

################################################################################
# LD2410 Sensor
################################################################################
ld2410:
  uart_id: ${device_internal_name}_uart_presence
  id: ${device_internal_name}_ld2410

################################################################################
# Time Sensor
################################################################################
time:
  - platform: homeassistant
    id: internal_time

################################################################################
# Text Sensors
################################################################################
text_sensor:
  #-------------------------------------------------------------------------------
  # ESP32 internal sensors
  #-------------------------------------------------------------------------------
  - platform: wifi_info
    ip_address:
      name: IP Address
      id: ${device_internal_name}_ip_address
    ssid:
      name: Connected SSID
      id: ${device_internal_name}_connected_ssid
    mac_address:
      name: Mac Wifi Address
      id: ${device_internal_name}_mac_address

  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true

  #-------------------------------------------------------------------------------
  # Custom Text sensors
  #-------------------------------------------------------------------------------
  - platform: template
    name: Uptime Human Readable
    id: ${device_internal_name}_uptime_human
    icon: mdi:clock-start

  #-------------------------------------------------------------------------------
  # LD240 Text sensors
  #-------------------------------------------------------------------------------
  - platform: ld2410
    version:
      name: "firmware version"
    mac_address:
      name: "mac address"

################################################################################
# Binary Sensors
################################################################################
binary_sensor:
  # ESP Status
  - platform: status
    name: "Status"
    id: ${device_internal_name}_device_status

  # LD2410
  - platform: ld2410
    has_target:
      name: Presence
      # Switch the screen off when no one is in the room
      on_state:
        then:
          - light.toggle:
              id: backlight
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target

sensor:
  #-------------------------------------------------------------------------------
  # ESP Generic Sensors
  #-------------------------------------------------------------------------------

  # Internal Temperature
  - platform: internal_temperature
    name: Internal Temperature
    id: device_temperature
    update_interval: ${device_sampling_time}

  # WiFi
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    id: ${device_internal_name}_wifi_signal_sensor
    update_interval: ${device_sampling_time}

  # Uptime
  - platform: uptime
    name: "Uptime Sensor"
    id: ${device_internal_name}_uptime_sensor
    update_interval: ${device_sampling_time}
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: ${device_internal_name}_uptime_human
            state: !lambda |-
              int seconds = round(id(${device_internal_name}_uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

  #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  # Additional sensors
  #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  #-------------------------------------------------------------------------------
  # SHT40 Sensors (0x44)
  #-------------------------------------------------------------------------------
  - platform: sht4x
    temperature:
      name: "Temperature"
      id: temperature
    humidity:
      name: "Relative Humidity"
      id: relative_humidity
    precision: High
    update_interval: ${device_sampling_time}

  #-------------------------------------------------------------------------------
  # GY-302/BH1750 Light Sensor (0x23)
  #-------------------------------------------------------------------------------
  - platform: bh1750
    name: "Illuminance"
    id: illuminance
    address: 0x23
    update_interval: ${device_sampling_time}

  #-------------------------------------------------------------------------------
  # CCS811 Air Quality Control Sensor (0x5A)
  #-------------------------------------------------------------------------------
  - platform: ccs811
    eco2:
      name: "eCO2 Value"
      id: ${device_internal_name}_eco2
    tvoc:
      name: "Total Volatile Organic Compound"
      id: ${device_internal_name}_tvoc
      icon: mdi:heat-wave
    version:
      name: CCS811 Version
      id: ${device_internal_name}_ccs811_version
    address: 0x5A
    temperature: ${device_internal_name}_dallas_temperature
    humidity: ${device_internal_name}_relative_humidity
    update_interval: ${device_sampling_time}

  #-------------------------------------------------------------------------------
  # LD2410D Millimeter Wave Sensor
  #-------------------------------------------------------------------------------
  - platform: ld2410
    light:
      name: light
    moving_distance:
      name: Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
    g0:
      move_energy:
        name: g0 move energy
      still_energy:
        name: g0 still energy
    g1:
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2:
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3:
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4:
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5:
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6:
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7:
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8:
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy

################################################################################
# Switch
################################################################################
switch:
  - platform: restart
    name: "Restart"
    id: device_restart

  - platform: safe_mode
    name: Use Safe Mode
    id: device_safe_mode

  - platform: ld2410
    # To fine tune
    engineering_mode:
      name: "engineering mode"
    # To switch the Bluetooth on and off
    bluetooth:
      name: "control bluetooth"
      restore_mode: RESTORE_DEFAULT_OFF #Switch the BT off

################################################################################
# Button
################################################################################
button:
  - platform: ld2410
    factory_reset:
      name: "factory reset"
    restart:
      name: "restart"
    query_params:
      name: query params

################################################################################
# Select
################################################################################
select:
  - platform: ld2410
    distance_resolution:
      name: "distance resolution"
    baud_rate:
      name: "baud rate"
    light_function:
      name: light function
    out_pin_level:
      name: out pin level

################################################################################
# Interval
################################################################################
interval:
  - interval: 10s
    then:
      - if:
          condition:
            wifi.connected:
          then:
            - lambda: |-
                id(wifi_connection) = true;
          else:
            - lambda: |-
                id(wifi_connection) = false;
