#VARIABLES
substitutions:
  device_name: esphome_mopeka_pro_check
  device_friendly_name: ESPHome Mopeka Pro Check
  device_ip_address: xxx.xxx.xxx.xxx

# Board Configuration
esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino
    version: 2.0.0

#-------------------------------------------------------------------------------
# Enable logging
#-------------------------------------------------------------------------------
logger:

#-------------------------------------------------------------------------------
# Enable Home Assistant API
#-------------------------------------------------------------------------------
api:
  reboot_timeout: 0s
  encryption:
    key: !secret api_encryption_key

ota:
  safe_mode: true
  password: !secret web_server_password

#-------------------------------------------------------------------------------
# WiFi
#-------------------------------------------------------------------------------
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

  manual_ip:
    static_ip: ${device_ip_address}
    gateway: !secret gateway_address
    subnet: !secret subnet_address

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_friendly_name}
    password: !secret web_server_password

time:
  - platform: homeassistant

#-------------------------------------------------------------------------------
# Bluetooth
#-------------------------------------------------------------------------------
bluetooth_proxy:
  active: true

# Bluetooth Low Energy Tracker Hub
esp32_ble_tracker:
  id: ${device_name}_ble_tracker
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

#-------------------------------------------------------------------------------
# Status led
#-------------------------------------------------------------------------------
status_led:
  pin:
    number: 2
    inverted: false

#-------------------------------------------------------------------------------
# Template Sensors
#-------------------------------------------------------------------------------
text_sensor:
  - platform: template
    name: Uptime Human Readable
    id: ${device_name}_uptime_human
    icon: mdi:clock-start

  - platform: wifi_info
    ip_address:
      name: IP Address
      id: ${device_name}_ip_address
    ssid:
      name: Connected SSID
      id: ${device_name}_connected_ssid
    mac_address:
      name: Mac Wifi Address
      id: ${device_name}_mac_address

  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true

#-------------------------------------------------------------------------------
# Sensors
#-------------------------------------------------------------------------------
sensor:
  #-------------------------------------------------------------------------------
  # ESP Generic Sensors
  #-------------------------------------------------------------------------------

  # ESP internal pemperature
  - platform: internal_temperature
    name: Internal Temperature
    id: ${device_name}_device_temperature
    update_interval: 120s

  # WiFi
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    id: ${device_name}_wifi_signal_sensor
    update_interval: 120s

  # Uptime
  - platform: uptime
    name: "Uptime Sensor"
    id: ${device_name}_uptime_sensor
    update_interval: 120s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: ${device_name}_uptime_human
            state: !lambda |-
              int seconds = round(id(${device_name}_uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

  #-------------------------------------------------------------------------------
  # Mopeka Pro Check BLE Sensor
  #-------------------------------------------------------------------------------
  - platform: mopeka_pro_check
    mac_address: ff:ff:ff:ff:ff:ff
    tank_type: custom
    custom_distance_full: 26cm
    custom_distance_empty: 1cm
    temperature:
      name: "LPG Sensor Temp"
      id: ${device_name}_lpg_tank_sensor_temp
    level:
      name: "LPG Level"
      id: ${device_name}_lpg_tank_level
    distance:
      name: "LPG Distance"
      id: ${device_name}_lpg_tank_distance
    battery_level:
      name: "LPG Sensor battery level"
      id: ${device_name}_lpg_tank_sensor_battery

#-------------------------------------------------------------------------------
# Binary Sensors
#-------------------------------------------------------------------------------
binary_sensor:
  # Room ESP Status
  - platform: status
    name: "Status"
    id: ${device_name}_device_status

#-------------------------------------------------------------------------------
# Switch
#-------------------------------------------------------------------------------
switch:
  # Restart Command
  - platform: restart
    name: "Restart"
    id: ${device_name}_device_restart

  #Safe Mode
  - platform: safe_mode
    name: "Restart (Safe Mode)"
    id: ${device_name}_device_restart_safe_mode
