# Your Wi-Fi SSID and password
wifi_ssid: "My-WiFi-SSID"
wifi_password: "My-WiFi-Password"

# Network settings
gateway_address: xxx.xxx.xxx.xxx
subnet_address: xxx.xxx.xxx.xxx
dns_address: xxx.xxx.xxx.xxx

#Webserver
web_server_user: "web_user"
web_server_password: "Web_Password"

#Api
api_password: "API_Password" #Deprcated, use encryption key
api_encryption_key: "api_encription_key"

#OTA
ota_password: "OTA_Password"

#MQTT
mqtt_ip: xxx.xxx.xxx.xxx
mqtt_user: mqtt
mqtt_password: "MQTT_Password"
