#Global variables
substitutions:
  device_name: esphome_ld2410c_mmwave
  device_friendly_name: ESPHome LD2410C MMwave
  update_time: 30s
  device_ip_address: xxx.xxx.xxx.xxx

# Board Configuration
esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

#-------------------------------------------------------------------------------
# Logging
#-------------------------------------------------------------------------------
logger:
  baud_rate: 0
  # Important!: This is to avoid conflicts with the LD2410C MMwave module

#-------------------------------------------------------------------------------
# Enable Home Assistant API
#-------------------------------------------------------------------------------
api:
  reboot_timeout: 0s
  encryption:
    key: !secret api_encryption_key

ota:
  safe_mode: true
  reboot_timeout: 10min
  num_attempts: 5
  password: !secret web_server_password

#-------------------------------------------------------------------------------
# WiFi
#-------------------------------------------------------------------------------
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

  manual_ip:
    static_ip: ${device_ip_address}
    gateway: !secret gateway_address
    subnet: !secret subnet_address

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_friendly_name}
    password: !secret web_server_password

time:
  - platform: homeassistant

#-------------------------------------------------------------------------------
# Web Server - Remember: Turn off if Blutooth Proxy is on!!!!
#-------------------------------------------------------------------------------
web_server:
  port: 80
  version: 2
  include_internal: true
  auth:
    username: !secret web_server_user
    password: !secret web_server_password
  local: true

captive_portal:

#-------------------------------------------------------------------------------
# Status led
#-------------------------------------------------------------------------------
status_led:
  pin:
    number: GPIO2
    inverted: false

#-------------------------------------------------------------------------------
# UART
#-------------------------------------------------------------------------------
uart:
  id: ${device_name}_uart_presence
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

#-------------------------------------------------------------------------------
# Templates
#-------------------------------------------------------------------------------

# Uptime
text_sensor:
  - platform: template
    name: Uptime Human Readable
    id: ${device_name}_uptime_human
    icon: mdi:clock-start

  #-------------------------------------------------------------------------------
  # ESP32 internal sensors
  #-------------------------------------------------------------------------------
  - platform: wifi_info
    ip_address:
      name: IP Address
      id: ${device_name}_ip_address
    ssid:
      name: Connected SSID
      id: ${device_name}_connected_ssid
    mac_address:
      name: Mac Wifi Address
      id: ${device_name}_mac_address

  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true

#-------------------------------------------------------------------------------
# Binary Sensors
#-------------------------------------------------------------------------------
binary_sensor:
  # Room ESP Status
  - platform: status
    name: "Status"
    id: ${device_name}_device_status

  # LD2410
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target

#-------------------------------------------------------------------------------
# Switch
#-------------------------------------------------------------------------------
switch:
  # Restart Command
  - platform: restart
    name: "Restart"
    id: ${device_name}_device_restart

  - platform: safe_mode
    name: use_safe_mode

#-------------------------------------------------------------------------------
# I2C - For future use
#-------------------------------------------------------------------------------
#i2c:
#  sda: GPIO21
#  scl: GPIO22
#  scan: False

ld2410:
  timeout: 5s
  max_move_distance: 6m
  max_still_distance: 0.75m

sensor:
  #-------------------------------------------------------------------------------
  # ESP Generic Sensors
  #-------------------------------------------------------------------------------

  # WiFi
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    id: ${device_name}_wifi_signal_sensor
    update_interval: 120s

  # Uptime
  - platform: uptime
    name: "Uptime Sensor"
    id: ${device_name}_uptime_sensor
    update_interval: 120s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: ${device_name}_uptime_human
            state: !lambda |-
              int seconds = round(id(${device_name}_uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

  #-------------------------------------------------------------------------------
  # Physical Sensors
  #-------------------------------------------------------------------------------

  # LD2410 MMwave Sensor Module
  - platform: ld2410
    moving_distance:
      name: Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
